# Write your MySQL query statement below
WITH EXAM_SUMMARY AS (
    SELECT 
        STUDENT_ID,
        SUBJECT_NAME,
        COUNT(*) AS EXAM_COUNT
    FROM EXAMINATIONS
    GROUP BY STUDENT_ID, SUBJECT_NAME 
)

SELECT 
    STU.STUDENT_ID,
    STU.STUDENT_NAME,
    SUJ.SUBJECT_NAME,
    IFNULL(EX.EXAM_COUNT,0) AS ATTENDED_EXAMS
FROM STUDENTS STU
CROSS JOIN SUBJECTS SUJ
LEFT JOIN EXAM_SUMMARY EX 
ON STU.STUDENT_ID = EX.STUDENT_ID AND SUJ.SUBJECT_NAME = EX.SUBJECT_NAME
ORDER BY STU.STUDENT_ID, SUBJECT_NAME