# Write your MySQL query statement below
WITH FIRST_SALES AS (
    SELECT 
        PRODUCT_ID,
        MIN(YEAR) AS FIRST_YEAR
    FROM SALES
    GROUP BY PRODUCT_ID
)

SELECT 
    FS.PRODUCT_ID,
    FS.FIRST_YEAR,
    S.QUANTITY,
    S.PRICE
FROM FIRST_SALES FS
INNER JOIN SALES S ON FS.PRODUCT_ID = S.PRODUCT_ID AND FS.FIRST_YEAR = S.YEAR