# Write your MySQL query statement below
WITH FIRST_LOGIN AS (SELECT 
    PLAYER_ID,
    MIN(EVENT_DATE) AS FIRST_LOGIN_DATE
FROM ACTIVITY
GROUP BY PLAYER_ID)

-- DAY, MONTH, YEAR, MINUTE
SELECT 
    ROUND(COUNT(*)/(SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY),2) AS FRACTION
FROM FIRST_LOGIN FL
INNER JOIN ACTIVITY ACT 
ON FL.PLAYER_ID = ACT.PLAYER_ID AND DATE_ADD(FL.FIRST_LOGIN_DATE, INTERVAL 1 DAY) = ACT.EVENT_DATE 