# Write your MySQL query statement below
SELECT 
    DATE_FORMAT(TRANS_DATE, '%Y-%m') AS MONTH,
    COUNTRY,
    COUNT(*) AS TRANS_COUNT,
    SUM(STATE='approved') AS APPROVED_COUNT,
    SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
    SUM(IF(STATE='approved',AMOUNT,0)) AS APPROVED_TOTAL_AMOUNT  
FROM TRANSACTIONS
GROUP BY MONTH, COUNTRY