# Write your MySQL query statement below
WITH LAST_CHANGE AS (
SELECT 
    PRODUCT_ID,
    NEW_PRICE AS PRICE
FROM PRODUCTS
WHERE (PRODUCT_ID, CHANGE_DATE) IN (
SELECT
    PRODUCT_ID,
    MAX(CHANGE_DATE) AS LAST_DATE
FROM PRODUCTS
WHERE CHANGE_DATE <= '2019-08-16'
GROUP BY PRODUCT_ID))

SELECT 
    P.PRODUCT_ID,
    IFNULL(LC.PRICE,10) AS PRICE
FROM (
    SELECT 
        DISTINCT(PRODUCT_ID) AS PRODUCT_ID
    FROM PRODUCTS
) P 
LEFT JOIN LAST_CHANGE LC ON P.PRODUCT_ID = LC.PRODUCT_ID

