# Write your MySQL query statement below

SELECT 
    S.USER_ID,
    IFNULL(ROUND(C.CONFIRMATION_RATE,2),0) AS CONFIRMATION_RATE
FROM SIGNUPS S
LEFT JOIN (
    SELECT 
        USER_ID,
        SUM(IF(ACTION = 'confirmed',1,0)) / COUNT(*) AS CONFIRMATION_RATE
    FROM CONFIRMATIONS
    GROUP BY USER_ID
) C ON S.USER_ID = C.USER_ID