# Write your MySQL query statement below


SELECT
    PERSON_NAME
FROM (SELECT
    TURN,
    PERSON_NAME,
    SUM(WEIGHT) OVER(ORDER BY TURN) AS T0TAL_WEIGHT 
FROM QUEUE
) T
WHERE T.T0TAL_WEIGHT <= 1000
ORDER BY TURN DESC
LIMIT 1